/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface InnerOne {
        "name": string;
    }
}
declare global {
    interface HTMLInnerOneElement extends Components.InnerOne, HTMLStencilElement {
    }
    var HTMLInnerOneElement: {
        prototype: HTMLInnerOneElement;
        new (): HTMLInnerOneElement;
    };
    interface HTMLElementTagNameMap {
        "inner-one": HTMLInnerOneElement;
    }
}
declare namespace LocalJSX {
    interface InnerOne {
        "name"?: string;
    }
    interface IntrinsicElements {
        "inner-one": InnerOne;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "inner-one": LocalJSX.InnerOne & JSXBase.HTMLAttributes<HTMLInnerOneElement>;
        }
    }
}
